name: Run Job Scraper

on:4567891011121314151617181920212223242526272829321$0
  workflow_dispatch: # Allows manual running
  schedule:
    - cron: '0 0,12 * * *' # Runs at midnight and noon UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin requests beautifulsoup4

      - name: Run Scraper
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FIREBASE_PROJECT_ID: my-job-porta
        run: python main_scraper.py
